filebeat.inputs:
- type: filestream
  id: my-filestream-id
  paths: 
    - /var/hw-app.log

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]

logging.json: true
logging.metrics.enabled: false