- name: Play Web - Create env variable in hello world app
  hosts: default
  become: yes
  remote_user: test
  tasks:
  - name: update docker container env var
    community.docker.docker_container:
      name: hello-world
      state: started
      env:
          HW_ENV_VAR: fromAnsible
